[project]
name = "FastAPI-app"
version = "0.1.0"
description = "A simple FastAPI application."

readme = "README.md"
requires-python = ">=3.11"

[project.dependencies]
fastapi = "*"
uvicorn = "*"
httpx = "*"

[project.optional-dependencies]
dev = { file = "dev-requirements.txt" }